apiVersion: v1
kind: Namespace
metadata:
  name: pgo

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-certificate
  namespace: pgo
spec:
  secretName: postgres-tls-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - cisb
  commonName: cisb-node-1.cisb.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - cisb-node-1.cisb.local
    - localhost
  issuerRef:
    name: db-vault-issuer
    kind: ClusterIssuer