apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-token
  namespace: cert-manager
data:
  token: aHZzLmNTZG9xRmY2Mzh2YUhRRXZ5NHRibjROcgo=

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: db-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_db/sign/server
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNYRENDQWdLZ0F3SUJBZ0lVVi9lbVpiR2dBK3ZjcE5TMlRzMDNZaUVYZVhFd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPVEEzTWpVd01Gb1hEVEk0TURReE56QTNNalV3TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVNFWUlaZ29hd3pJUFk4bnFqNGR3c0hLZ05wUzE2UTNtb1hIVGFrL1BSc00xUHhjNDlSZTVkc2h5Cm93MWl4UnBmWk9OQkN2OVc3TENhdEd1VmhjbjRMcU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQWExJbCtSMWlreTNhUkpYS2RubHF1empIb2xNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFERHBHV2owVmNmR1RjVloyelZtd1BGWm5vS3NhczIrMEZkejJUUXJLZE9Pd0lnCko3ZUpDaUxWT2xTeHVpMDhRU1hMOTJrT1dNeHJHc0xHT0pJQzFacEhYd0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: db-vault-client-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_db/sign/client
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNYRENDQWdLZ0F3SUJBZ0lVVi9lbVpiR2dBK3ZjcE5TMlRzMDNZaUVYZVhFd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPVEEzTWpVd01Gb1hEVEk0TURReE56QTNNalV3TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVNFWUlaZ29hd3pJUFk4bnFqNGR3c0hLZ05wUzE2UTNtb1hIVGFrL1BSc00xUHhjNDlSZTVkc2h5Cm93MWl4UnBmWk9OQkN2OVc3TENhdEd1VmhjbjRMcU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQWExJbCtSMWlreTNhUkpYS2RubHF1empIb2xNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFERHBHV2owVmNmR1RjVloyelZtd1BGWm5vS3NhczIrMEZkejJUUXJLZE9Pd0lnCko3ZUpDaUxWT2xTeHVpMDhRU1hMOTJrT1dNeHJHc0xHT0pJQzFacEhYd0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: auth-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_auth/sign/server
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNYRENDQWdLZ0F3SUJBZ0lVVi9lbVpiR2dBK3ZjcE5TMlRzMDNZaUVYZVhFd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPVEEzTWpVd01Gb1hEVEk0TURReE56QTNNalV3TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVNFWUlaZ29hd3pJUFk4bnFqNGR3c0hLZ05wUzE2UTNtb1hIVGFrL1BSc00xUHhjNDlSZTVkc2h5Cm93MWl4UnBmWk9OQkN2OVc3TENhdEd1VmhjbjRMcU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQWExJbCtSMWlreTNhUkpYS2RubHF1empIb2xNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFERHBHV2owVmNmR1RjVloyelZtd1BGWm5vS3NhczIrMEZkejJUUXJLZE9Pd0lnCko3ZUpDaUxWT2xTeHVpMDhRU1hMOTJrT1dNeHJHc0xHT0pJQzFacEhYd0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_http/sign/server
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNYRENDQWdLZ0F3SUJBZ0lVVi9lbVpiR2dBK3ZjcE5TMlRzMDNZaUVYZVhFd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPVEEzTWpVd01Gb1hEVEk0TURReE56QTNNalV3TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRVNFWUlaZ29hd3pJUFk4bnFqNGR3c0hLZ05wUzE2UTNtb1hIVGFrL1BSc00xUHhjNDlSZTVkc2h5Cm93MWl4UnBmWk9OQkN2OVc3TENhdEd1VmhjbjRMcU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQWExJbCtSMWlreTNhUkpYS2RubHF1empIb2xNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFERHBHV2owVmNmR1RjVloyelZtd1BGWm5vS3NhczIrMEZkejJUUXJLZE9Pd0lnCko3ZUpDaUxWT2xTeHVpMDhRU1hMOTJrT1dNeHJHc0xHT0pJQzFacEhYd0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token