apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-token
  namespace: cert-manager
data:
  token: aHZzLmowYUVUQ3d1eENQMkNxNTNmNlVZRUhDTAo=

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: db-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_db/sign/server
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXekNDQWdLZ0F3SUJBZ0lVR0ZFTUNEY2tuRVVBWmVvdWo0Z1JqRGkxcVBjd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPREl3TURNd01Gb1hEVEk0TURReE5qSXdNRE13TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUFZbVYvaVFZZWtIaU05YklCUTZOOTMwdUxMSS9peDA2eDczL1hyVUUzQ041YklyMjZvOFZVVVpQClhmcEl0YWx0N2FCYWg4WkJoY1FPTldEbU8rdENoS05DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQUDNyeUEwMWtaZXlGVXl3T0ZoeXRCQ3ZEK3NNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUNnbllFQU5MbFlwaHgwaHBFaDlYRDFkMmFPZ2xuWEQ4OXpmMk1KdzUrUE5BaUFxCmV3b0dYcGtWVlZnZTJWZXVLWVNjZGpWWGZIaWlqZTJUOTYyN1ZuWkpQdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: db-vault-client-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_db/sign/client
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXekNDQWdLZ0F3SUJBZ0lVR0ZFTUNEY2tuRVVBWmVvdWo0Z1JqRGkxcVBjd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPREl3TURNd01Gb1hEVEk0TURReE5qSXdNRE13TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUFZbVYvaVFZZWtIaU05YklCUTZOOTMwdUxMSS9peDA2eDczL1hyVUUzQ041YklyMjZvOFZVVVpQClhmcEl0YWx0N2FCYWg4WkJoY1FPTldEbU8rdENoS05DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQUDNyeUEwMWtaZXlGVXl3T0ZoeXRCQ3ZEK3NNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUNnbllFQU5MbFlwaHgwaHBFaDlYRDFkMmFPZ2xuWEQ4OXpmMk1KdzUrUE5BaUFxCmV3b0dYcGtWVlZnZTJWZXVLWVNjZGpWWGZIaWlqZTJUOTYyN1ZuWkpQdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: auth-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_auth/sign/server
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXekNDQWdLZ0F3SUJBZ0lVR0ZFTUNEY2tuRVVBWmVvdWo0Z1JqRGkxcVBjd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPREl3TURNd01Gb1hEVEk0TURReE5qSXdNRE13TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUFZbVYvaVFZZWtIaU05YklCUTZOOTMwdUxMSS9peDA2eDczL1hyVUUzQ041YklyMjZvOFZVVVpQClhmcEl0YWx0N2FCYWg4WkJoY1FPTldEbU8rdENoS05DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQUDNyeUEwMWtaZXlGVXl3T0ZoeXRCQ3ZEK3NNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUNnbllFQU5MbFlwaHgwaHBFaDlYRDFkMmFPZ2xuWEQ4OXpmMk1KdzUrUE5BaUFxCmV3b0dYcGtWVlZnZTJWZXVLWVNjZGpWWGZIaWlqZTJUOTYyN1ZuWkpQdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_http/sign/server
    server: https://cisb-node-1:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXekNDQWdLZ0F3SUJBZ0lVR0ZFTUNEY2tuRVVBWmVvdWo0Z1JqRGkxcVBjd0NnWUlLb1pJemowRUF3SXcKZ1lzeEN6QUpCZ05WQkFZVEFrbFVNUTR3REFZRFZRUUlFd1ZKZEdGc2VURU9NQXdHQTFVRUJ4TUZWVzVwUWxNeApJVEFmQmdOVkJBb1RHRWxGUlVVZ1UzUjFaR1Z1ZENCQ2NtRnVZMmdnTVRBeE9URWlNQ0FHQTFVRUN4TVpTVVZGClJTQlRWRUl4TURFNUlFTkpVMElnVW05dmRDQkRRVEVWTUJNR0ExVUVBeE1NUTBsVFFpQlNiMjkwSUVOQk1CNFgKRFRJek1EUXhPREl3TURNd01Gb1hEVEk0TURReE5qSXdNRE13TUZvd2dZc3hDekFKQmdOVkJBWVRBa2xVTVE0dwpEQVlEVlFRSUV3VkpkR0ZzZVRFT01Bd0dBMVVFQnhNRlZXNXBRbE14SVRBZkJnTlZCQW9UR0VsRlJVVWdVM1IxClpHVnVkQ0JDY21GdVkyZ2dNVEF4T1RFaU1DQUdBMVVFQ3hNWlNVVkZSU0JUVkVJeE1ERTVJRU5KVTBJZ1VtOXYKZENCRFFURVZNQk1HQTFVRUF4TU1RMGxUUWlCU2IyOTBJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRUFZbVYvaVFZZWtIaU05YklCUTZOOTMwdUxMSS9peDA2eDczL1hyVUUzQ041YklyMjZvOFZVVVpQClhmcEl0YWx0N2FCYWg4WkJoY1FPTldEbU8rdENoS05DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQUDNyeUEwMWtaZXlGVXl3T0ZoeXRCQ3ZEK3NNQW9HQ0NxRwpTTTQ5QkFNQ0EwY0FNRVFDSUNnbllFQU5MbFlwaHgwaHBFaDlYRDFkMmFPZ2xuWEQ4OXpmMk1KdzUrUE5BaUFxCmV3b0dYcGtWVlZnZTJWZXVLWVNjZGpWWGZIaWlqZTJUOTYyN1ZuWkpQdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token