apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-token
  namespace: cert-manager
data:
  token: TOKEN

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: db-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_db/sign/server
    server: https://cisb-node-1:8200
    caBundle: CABUNDLE
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: db-vault-client-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_db/sign/client
    server: https://cisb-node-1:8200
    caBundle: CABUNDLE
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: auth-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_auth/sign/server
    server: https://cisb-node-1:8200
    caBundle: CABUNDLE
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-vault-server-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_auth/sign/server
    server: https://cisb-node-1:8200
    caBundle: CABUNDLE
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token