apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
  namespace: postgres
data:
  postgresql.conf: |
    listen_addresses = '*'
    port = 5432
    hba_file = '/etc/postgresql/pg_hba.conf'
    data_directory = '/var/lib/postgresql/data/'
    password_encryption = scram-sha-256
    ssl = on
    ssl_ca_file = '/etc/cert/ca.crt'
    ssl_cert_file = '/etc/cert/tls.crt'
    ssl_key_file = '/etc/cert/tls.key'
    ssl_ciphers = 'TLSv1.2:TLSv1.3:!aNULL:!eNULL'
    ssl_prefer_server_ciphers = on
  pg_hba.conf: |
    host all all 127.0.0.1/32 trust
    hostssl all all 0.0.0.0/0 cert clientcert=verify-full

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: postgres
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 70
      containers:
        - name: postgres
          image: postgres:alpine
          args: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-conf
              mountPath: /etc/postgresql/
            - name: cert
              mountPath: /etc/cert
            - name: data
              mountPath: /var/lib/postgresql/data/
              readOnly: false
          env:
            - name: POSTGRES_PASSWORD
              value: example
      volumes:
        - name: postgresql-conf
          configMap: 
            name: postgres-conf
            items:
              - key: "postgresql.conf"
                path: "postgresql.conf"
              - key: "pg_hba.conf"
                path: "pg_hba.conf"
        - name: cert
          secret:
            secretName: postgres-tls
            defaultMode: 384
        - name: data
          persistentVolumeClaim:
            claimName: postgres-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service-lb
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer